# Travis CI script

language: c

cache: ccache

sudo: required

addons:
  apt:
    packages:
    - uuid-dev

env:
- BUILD_TYPE=default ZMQ_REPO_URL=https://github.com/42ity/libzmq.git ZMQ_REPO_BRANCH=4.2.0-FTY-master
- BUILD_TYPE=default ZMQ_REPO_URL=https://github.com/42ity/libzmq.git ZMQ_REPO_BRANCH=4.2.0-FTY-master WITH_LIBSODIUM=1
#- BUILD_TYPE=default ZMQ_REPO=zeromq2-x
- BUILD_TYPE=default ZMQ_REPO=zeromq3-x
- BUILD_TYPE=default ZMQ_REPO=zeromq4-x WITH_LIBSODIUM=1
- BUILD_TYPE=default ZMQ_REPO=libzmq    WITH_LIBSODIUM=1
#- BUILD_TYPE=valgrind ZMQ_REPO=zeromq2-x
#- BUILD_TYPE=valgrind ZMQ_REPO=zeromq3-x
#- BUILD_TYPE=valgrind ZMQ_REPO=zeromq4-x WITH_LIBSODIUM=1
#- BUILD_TYPE=valgrind ZMQ_REPO=libzmq    WITH_LIBSODIUM=1
#- BUILD_TYPE=valgrind ZMQ_REPO=zeromq2-x ADDRESS_SANITIZER=enabled
#- BUILD_TYPE=valgrind ZMQ_REPO=zeromq3-x ADDRESS_SANITIZER=enabled
#- BUILD_TYPE=valgrind ZMQ_REPO=zeromq4-x ADDRESS_SANITIZER=enabled WITH_LIBSODIUM=1
#- BUILD_TYPE=valgrind ZMQ_REPO=libzmq    ADDRESS_SANITIZER=enabled WITH_LIBSODIUM=1
#- BUILD_TYPE=qt-android
#- BUILD_TYPE=check-py

matrix:
  include:
  - env: BUILD_TYPE=valgrind ZMQ_REPO=zeromq3-x
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - valgrind
        - uuid-dev
  - env: BUILD_TYPE=valgrind ZMQ_REPO=zeromq4-x WITH_LIBSODIUM=1
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - valgrind
        - uuid-dev

  - env: BUILD_TYPE=valgrind ZMQ_REPO_URL=https://github.com/42ity/libzmq.git
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - valgrind
        - uuid-dev

  - env: BUILD_TYPE=valgrind ZMQ_REPO_URL=https://github.com/42ity/libzmq.git ZMQ_REPO_BRANCH=4.2.0-FTY-master WITH_LIBSODIUM=1
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - valgrind
        - uuid-dev

#  - env: BUILD_TYPE=valgrind ZMQ_REPO=libzmq WITH_LIBSODIUM=1
#    os: linux
#    dist: trusty
#    sudo: required
#    addons:
#      apt:
#        packages:
#        - valgrind
#        - uuid-dev

  - env: BUILD_TYPE=selftest ZMQ_REPO=zeromq3-x ADDRESS_SANITIZER=enabled
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - uuid-dev
  - env: BUILD_TYPE=selftest ZMQ_REPO_URL=https://github.com/42ity/libzmq.git ZMQ_REPO_BRANCH=4.2.0-FTY-master ADDRESS_SANITIZER=enabled
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - uuid-dev

  - env: BUILD_TYPE=selftest ZMQ_REPO=zeromq4-x ADDRESS_SANITIZER=enabled WITH_LIBSODIUM=1
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - uuid-dev

  - env: BUILD_TYPE=selftest ZMQ_REPO=libzmq ADDRESS_SANITIZER=enabled WITH_LIBSODIUM=1 ZMQ_CONFIG_OPTS_DRAFT=no
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - uuid-dev
  - env: BUILD_TYPE=selftest ZMQ_REPO=libzmq ADDRESS_SANITIZER=enabled WITH_LIBSODIUM=1 ZMQ_CONFIG_OPTS_DRAFT=yes
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - uuid-dev

  - env: BUILD_TYPE=selftest ZMQ_REPO_URL=https://github.com/42ity/libzmq.git ZMQ_REPO_BRANCH=4.2.0-FTY-master ADDRESS_SANITIZER=enabled WITH_LIBSODIUM=1
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - uuid-dev
  - env: BUILD_TYPE=selftest ZMQ_REPO_URL=https://github.com/42ity/libzmq.git ZMQ_REPO_BRANCH=4.2.0-FTY-master ADDRESS_SANITIZER=enabled WITH_LIBSODIUM=1 LIBSODIUM_REPO_URL=https://github.com/42ity/libsodium.git LIBSODIUM_REPO_BRANCH=1.0.5-FTY-master
    os: linux
    dist: trusty
    sudo: required
    addons:
      apt:
        packages:
        - uuid-dev


before_script:
#- sudo apt-get install uuid-dev
- ./autogen.sh

# Build and check this project according to the BUILD_TYPE
script: travis_wait 30 ./ci_build.sh
